# Generated by Django 5.2.12 on 2026-03-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cert_emissor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Emissor do Certificado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cert_nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome no Certificado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cert_valido_ate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certificado válido até'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(blank=True, help_text='Somente números, 11 dígitos', max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
