# Generated by Django 4.2.29 on 2026-03-17 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Resposta'), ('EM_ANDAMENTO', 'Em Andamento'), ('SUSPENSO', 'Suspenso'), ('ENCERRADO', 'Encerrado'), ('EXTINTO', 'Extinto')], default='AGUARDANDO', max_length=20)),
                ('tipo', models.CharField(choices=[('DIREITO', 'Por Direito'), ('EQUIDADE', 'Por Equidade')], default='DIREITO', max_length=10)),
                ('demandado_nome', models.CharField(max_length=200, verbose_name='Nome do Demandado')),
                ('demandado_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Demandado')),
                ('descricao', models.TextField(verbose_name='Descrição do Litígio')),
                ('valor_reclamado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor Reclamado (R$)')),
                ('sede', models.CharField(blank=True, max_length=100, verbose_name='Sede da Arbitragem')),
                ('confidencial', models.BooleanField(default=True, verbose_name='Processo Confidencial')),
                ('arbitro', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'ARBITRO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_como_arbitro', to=settings.AUTH_USER_MODEL, verbose_name='Árbitro')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('demandante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_como_demandante', to=settings.AUTH_USER_MODEL, verbose_name='Demandante')),
            ],
            options={
                'verbose_name': 'Processo Arbitral',
                'verbose_name_plural': 'Processos Arbitrais',
                'ordering': ['-created_at'],
                'permissions': [('pode_atribuir_arbitro', 'Pode atribuir árbitro ao processo'), ('pode_encerrar_processo', 'Pode encerrar processo'), ('pode_ver_confidencial', 'Pode ver processos confidenciais')],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='processos/documentos/%Y/%m/')),
                ('descricao', models.TextField(blank=True)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.TextField(verbose_name='Descrição do Andamento')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='processos.processo')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Andamento',
                'verbose_name_plural': 'Andamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
