# Generated by Django 4.2.29 on 2026-03-17 03:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaCustas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instituicao', models.CharField(choices=[('CEMAPE', 'CEMAPE'), ('CAMARB', 'CAMARB')], max_length=10, verbose_name='Instituição')),
                ('tipo_procedimento', models.CharField(choices=[('ARBITRAGEM', 'Arbitragem'), ('MEDIACAO', 'Mediação')], max_length=15, verbose_name='Tipo de Procedimento')),
                ('tipo_taxa', models.CharField(choices=[('REGISTRO', 'Taxa de Registro'), ('ADMINISTRACAO', 'Taxa de Administração'), ('HONORARIOS', 'Honorários dos Árbitros/Mediadores')], max_length=15, verbose_name='Tipo de Taxa')),
                ('metodo_calculo', models.CharField(choices=[('PERCENTUAL_DEMANDA', 'Percentual da Demanda (com piso/teto)'), ('FIXO', 'Valor Fixo Único'), ('INTERPOLACAO', 'Interpolação Linear por Faixa'), ('BASE_MAIS_PCT', 'Base + % sobre Excedente da Faixa'), ('FAIXA_FIXA', 'Valor Fixo por Faixa'), ('HORA_TRABALHADA', 'Por Hora Trabalhada')], max_length=20, verbose_name='Método de Cálculo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True)),
                ('vigente_a_partir', models.DateField(verbose_name='Vigente a partir de')),
            ],
            options={
                'verbose_name': 'Tabela de Custas',
                'verbose_name_plural': 'Tabelas de Custas',
                'ordering': ['instituicao', 'tipo_procedimento', 'tipo_taxa'],
                'unique_together': {('instituicao', 'tipo_procedimento', 'tipo_taxa', 'vigente_a_partir')},
            },
        ),
        migrations.CreateModel(
            name='FaixaCustas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveSmallIntegerField(help_text='Ordem de exibição/avaliação')),
                ('demanda_min', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='VD mínimo (R$)')),
                ('demanda_max', models.DecimalField(blank=True, decimal_places=2, help_text='Deixar em branco para faixa aberta (último escalão)', max_digits=18, null=True, verbose_name='VD máximo (R$)')),
                ('valor_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor mín da taxa (R$)')),
                ('valor_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor máx da taxa (R$)')),
                ('valor_base', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor base (R$)')),
                ('pct_excedente', models.DecimalField(blank=True, decimal_places=4, help_text='Ex: 1.98 para 1,980%', max_digits=8, null=True, verbose_name='% sobre excedente')),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor fixo / Valor hora (R$)')),
                ('valor_teto_faixa', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Teto desta faixa (R$)')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='calculadora.tabelacustas')),
            ],
            options={
                'verbose_name': 'Faixa de Custas',
                'verbose_name_plural': 'Faixas de Custas',
                'ordering': ['tabela', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoCalculadora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instituicao', models.CharField(choices=[('CEMAPE', 'CEMAPE'), ('CAMARB', 'CAMARB')], max_length=10, verbose_name='Instituição')),
                ('tipo_procedimento', models.CharField(choices=[('ARBITRAGEM', 'Arbitragem'), ('MEDIACAO', 'Mediação')], max_length=15, verbose_name='Procedimento')),
                ('chave', models.CharField(max_length=60, verbose_name='Chave')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Valor')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração da Calculadora',
                'verbose_name_plural': 'Configurações da Calculadora',
                'ordering': ['instituicao', 'tipo_procedimento', 'chave'],
                'unique_together': {('instituicao', 'tipo_procedimento', 'chave')},
            },
        ),
    ]
